### ISSUE TITLE
Cannot build and start the application properly.

### ISSUE THREAD

**Issue by avittecoqDAJ** [librelioniv2/ios-testmatos#12]
After pulling the latest changes of iOS9 branch, I'm still not able to build and run the app properly.
I've got a SIGABRT signal raising.

I think, I've done something wrong somewhere. @lgdi can you send me the steps to follow to build testskis from a clean clone of the iOS9 branch ?
What files to changes and how ?

Thanks a lot.

**Comment by deepiksdev** [comment]
@avittecoqDAJ 

> I've got a SIGABRT signal raising.

Please provide details about the error message.

> I think, I've done something wrong somewhere. @lgdi can you send me the steps to follow to build testskis from a clean clone of the iOS9 branch ?
> What files to changes and how ?

The build process using the script target is documented here: https://github.com/libreliodev/iOS/wiki/Building#using-the-script-target

You just need to enter the path to the Test Ski folder in Dropbox into `path.txt`, and it should work. Please note that due to issue #11, the name of the folder in Dropbox will likely change in the near future.

**Comment by deepiksdev** [comment]
@avittecoqDAJ The test Ski folder in Dropbox has been renamed to `testskis2014` . You should update `path.txt`accordingly.

**Comment by avittecoqDAJ** [comment]
I'm finally able to build and launch the application.
The trick is to read the documentation linked within the documentation @lgdi gave me before.

Thanks
